name: CI for Personal Site
on: [push]

env:
  NEXT_TELEMETRY_DISABLED: 1
  
jobs:
  frontend_compile:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install deps
        run: yarn
      - name: Run Prettier
        run: yarn format
      - name: Run ESLint
        run: yarn lint
      - name: Build project
        run: yarn build
