name: CICD for Personal Site
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  NEXT_TELEMETRY_DISABLED: 1
  
jobs:
  frontend_compile:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install deps
        run: npm install
      - name: Run Prettier
        run: npm run format:check
      - name: Run ESLint
        run: npm run lint
      - name: Build project
        run: npm run build
